### ISSUE TITLE
Used home-brew to install WezTerm, but cannot find WezTerm.app

### ISSUE THREAD

**Issue by ironfish** [wez/homebrew-wezterm#1]
I can launch WezTerm from the command line in terminal, but cannot find the WezTerm.app setup anywhere.

**Comment by ironfish** [comment]
Here is an example of how `Hyper.app` does it.
- https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/hyper.rb

**Comment by wez** [comment]
Please see also: https://github.com/wez/wezterm/issues/501

**Comment by jasikpark** [comment]
Perhaps automatic CI for nightly build could be added so that releasing the nightly casks isn't too much of a hassle? wezterm should not be a formulae, to be honest.
https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app
